server:
  port: 20181

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SENSOR_DB_URL:jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_SENSOR?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SENSOR_DB_USERNAME:root}
    password: ${SENSOR_DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

sensor:
  mqtt:
    enabled: ${SENSOR_MQTT_ENABLED:false}
